name: Update translation, readme and Rust packaging files in main branch automatically
on:
  push:
    branches:
      - main
    paths-ignore:
      - po/*
      - README.md
      - debian/control

env:
  apt_dependencies: >-
    ca-certificates curl dconf-cli gcc gettext git libnss-wrapper libsmbclient-dev
    libwbclient-dev pkg-config protobuf-compiler python3-coverage samba sudo

jobs:
  update-po:
    name: Update po files
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt update
          sudo DEBIAN_FRONTEND=noninteractive apt install -y gettext
      # Checkout code with git
      - uses: actions/checkout@v3
        with:
          ref: main
      # Install go
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      # Update po if needed
      - name: Check po files
        id: checkpo
        run: |
          set -eu

          hasModif="false"
          go generate ./internal/i18n/
          # Exclude line diffs only
          MODIFIED=$(git difftool -y -x "diff -Nup -I '^#: '" po/)
          if [ -n "$MODIFIED" ]; then
            hasModif="true"
          fi
          echo "modified=${hasModif}" >> $GITHUB_ENV
      - name: Create Pull Request
        if: ${{ env.modified == 'true' }}
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Auto update po files
          title: Auto update po files
          labels: po, automated pr
          body: "[Auto-generated pull request](https://github.com/ubuntu/adsys/actions/workflows/auto-updates.yaml) by GitHub Action"
          branch: auto-update-po
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Push branch
        if: ${{ env.modified == 'true' }}
        run: |
          git push origin auto-update-po:main

  update-readme-clid-ref:
    name: Update readme and CLI ref files
    # This should just be "after", but we don't want the 2 jobs to push at the same time
    needs: update-po
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt update
          sudo DEBIAN_FRONTEND=noninteractive apt install -y ${{ env.apt_dependencies }}
      # Checkout code with git
      - uses: actions/checkout@v3
        with:
          ref: main
      # Install go
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      # Try updating README
      - name: Check README file
        id: checkreadme
        run: |
          set -eu

          hasModif="false"
          cd cmd/adsysd
          go run ../generate_completion_documentation.go update-readme
          go run ../generate_completion_documentation.go update-doc-cli-ref
          MODIFIED=$(git status --porcelain --untracked-files=no)
          if [ -n "$MODIFIED" ]; then
            hasModif="true"
          fi
          echo "modified=${hasModif}" >> $GITHUB_ENV
      - name: Create Pull Request
        if: ${{ env.modified == 'true' }}
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Auto update readme files
          title: Auto update readme files
          labels: readme, automated pr
          body: "[Auto-generated pull request](https://github.com/ubuntu/adsys/actions/workflows/auto-updates.yaml) by GitHub Action"
          branch: auto-update-readme-cli-ref
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Push branch
        if: ${{ env.modified == 'true' }}
        run: |
          git push origin auto-update-readme-cli-ref:main

  update-rust-packaging:
    name: Update packaging related Rust files
    needs: update-readme-clid-ref
    runs-on: ubuntu-latest
    # Right now, ubuntu 22.04 does not have the dh-cargo-vendored-sources script that is needed to
    # run this job, so we need to run it inside a rolling container to get the latest version possible.
    # This should be updated as soon as the dh-cargo version with the mentioned script gets ported to
    # 22.04 or ubuntu-latest changes to a more recent version.
    container:
      image: ubuntu:rolling
    steps:
      - name: Install dependencies
        run: |
          DEBIAN_FRONTEND=noninteractive apt update
          DEBIAN_FRONTEND=noninteractive apt install -y cargo dh-cargo git jq
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Vendor the dependencies
        run: |
          cargo vendor vendor_rust/
      - name: Update XS-Vendored-Sources-Rust
        run: |
          set -eu
          export CARGO_VENDOR_DIR=vendor_rust/
          VENDORED_SOURCES=$(/usr/share/cargo/bin/dh-cargo-vendored-sources 2>&1 || true)
          OUTPUT=$(echo "$VENDORED_SOURCES" | grep ^XS-Vendored-Sources-Rust: || true)
          if [ -z "$OUTPUT" ]; then
            echo "XS-Vendored-Sources-Rust is up to date. No change is needed.";
            exit 0
          fi
          sed -i "s/^XS-Vendored-Sources-Rust:.*/$OUTPUT/" debian/control
          echo "modified=true" >> $GITHUB_ENV
        shell: bash
      - name: Create Pull Request
        if: ${{ env.modified == 'true' }}
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Auto update packaging related Rust files
          title: Auto update packaging related Rust files
          labels: control, automated pr
          body: "[Auto-generated pull request](https://github.com/ubuntu/adsys/actions/workflows/auto-updates.yaml) by GitHub Action"
          branch: auto-update-rust-packaging
          delete-branch: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Push branch
        if: ${{ env.modified == 'true' }}
        run: |
          git push origin auto-update-rust-packaging:main
