name: Test VPN connection

on:
  workflow_dispatch:

jobs:
  setup-vpn-connection:
    name: Setup VPN connection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/azure-sstpc-vpn
        with:
          gateway: azuregateway-9f060069-b954-4934-8cb1-6189a175268f-a48a8c3c6f21.vpn.azure.com
          ca: ${{ secrets.VPN_CA }}
          cert: ${{ secrets.VPN_CERT }}
          key: ${{ secrets.VPN_KEY }}
          routes: 10.1.0.0/16

      - name: Start SSH session
        uses: GabrielNagy/debug-via-ssh@main
        with:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
          SSH_PASS: ${{ secrets.SSH_PASSWORD }}
